### ISSUE TITLE
Flag proportion

### ISSUE THREAD

**Issue by jeansouza** [rostegg/public-ip-gnome-extension#13]
Is there any way to keep the flag image proportion? Right now is being shown as a square, instead of a rectangle.

I cloned the repo and tried to fix, changing css, but with no success.

**Comment by rostegg** [comment]
Well, icon style set at [this](https://github.com/rostegg/public-ip-gnome-extension/blob/8fd8bf9f56566f31961e89cc930996b540d3d896/extension.js#L168) line.  

So, if you want to define custom style, you should define selector in [stylesheets.css](https://github.com/rostegg/public-ip-gnome-extension/blob/8fd8bf9f56566f31961e89cc930996b540d3d896/stylesheet.css), something like this:
```
.custom-icon-style {
    height: 32px;
    width: 20px;
}
```
And then change style to your own:
```
style_class: 'custom-icon-style'
```

I will check it tomorrow, because I'm a little bit busy now, and can't access my desktop.  

But I'm not sure if this is a necessary change, since the standard style is quite clearly displayed and takes up less space on the panel.

**Comment by jeansouza** [comment]
Do you think that would be a problem to create a config for this?

I could implement this and create a pull request, leaving for the user to choose the format of the icon (using as default the current behavior, of course).

**Comment by rostegg** [comment]
I do not think that it will be difficult to implement, but I believe that it will be an unnecessary feature.

 As I mentioned [here](https://github.com/rostegg/public-ip-gnome-extension/issues/11#issuecomment-553894933), this extension was created for simple purpose, just to show if ip has changed, for example when using vpn, but over time, it began to acquire features that was not needed here at all, but was still required by some users. 

So, I will be grateful for your contribution and I will gladly accept the pull request, but later that feature will move to a new extension, mentioned in #11

**Comment by jeansouza** [comment]
Ok, thanks! :)
