### ISSUE TITLE
Error launching extension - NMClient

### ISSUE THREAD

**Issue by MikeDawg** [rostegg/public-ip-gnome-extension#7]
Getting the following error when attempting to install:

Error: Requiring NMClient, version none: Typelib file for namespace 'NMClient' (any version) not found

GNOME Shell 3.32.2

Name        : gnome-shell
Version     : 3.32.2
Release     : 2.fc30
Architecture: x86_64

LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 30 (Thirty)
Release:	30
Codename:	Thirty

**Comment by rostegg** [comment]
Well, after quick research, I found [this](https://bugzilla.gnome.org/show_bug.cgi?id=789811).  
The `libnm-glib` is deprecated and replaced by `libnm`, so problems starting from here
Most likely, you don't have the necessary libraries installed or incorrectly installed `libnm`  

First of all, check if `libnm` is working: `nmcli --version`

Next, same [problem](https://github.com/micheleg/dash-to-dock/issues/398) was with missing Clutter dependencies, and fixed by installation those packages: `gir1.2-clutter-1.0 gir1.2-clutter-gst-3.0 gir1.2-gtkclutter-1.0`  

After searching [info](https://koji.fedoraproject.org/koji/buildinfo?buildID=1278758) about your package version, in [x86_64 build.log](https://kojipkgs.fedoraproject.org//packages/gnome-shell/3.32.2/2.fc30/data/logs/x86_64/build.log), seems. like `libnm` is installed, but compared to the [Ubuntu package](https://packages.ubuntu.com/bionic/gnome-shell), seems like some dependencies, for example `gir1.2-nm-1.0`
So, `dpkg -l gir1.2-n*` for check, if some of required libs is installed  

My output:  

```
un  gir1.2-networkmanager-1.0                      <none>                       <none>                       (no description available)
ii  gir1.2-nm-1.0:amd64                            1.10.14-0ubuntu2             amd64                        GObject introspection data for the libnm library
ii  gir1.2-nma-1.0:amd64                           1.8.10-2ubuntu2              amd64                        GObject introspection data for libnma
```

Seems, like `gir1.2-networkmanager-1.0, gir1.2-nm-1.0, gir1.2-nma-1.0`is related to NetworkManager.  

So, I see only two ways to solve the problem:
1. Reinstall/update gnome desktop (not sure if update will definitely help, but reinstall to latest version must fix problem).
2. Find all necessary missing libraries and install manually (`gir1.2-networkmanager-1.0, gir1.2-nm-1.0, gir1.2-nma-1.0`, maybe there are others)

Unfortunately, I can’t reproduce the bug to test it myself.

Are you using any other extensions that affect networking?

**Comment by MikeDawg** [comment]
Thank you @rostegg 

The only thing I changed, there was a second "show ip" or similar extension installed already. I removed it, and this extension. Then, I re-added this extension, and it worked fine.

Sorry for clumsily missing the installed version of a similar extension.
